prop:
  filepath: D:/photo/

server:
  port: 8089
  servlet:
    context-path: '/ailybg'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ailydb?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123@qwe
  jackson:
    date-format: 'yyyy-MM-dd'

  resources: # 静态资源路径
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/

  thymeleaf:
    cache: false  # 使用模板缓存
    suffix: .html
    encoding: UTF-8
    prefix: classpath:/templates/
    mode: HTML5
  mybatis:
    type-aliases-package: com.aaa.dao
    mapper-locations: classpath:mapper/*.xml
